### ISSUE TITLE
handle memory allocation error more gracefully, source image locked

### ISSUE THREAD

**Issue by chalkie666** [clij/clij#19]
In the case of an openCL memory allocation error, 
eg when supplying too large a kernel for RL deconvolution
[ERROR] Module threw exception
net.haesleinhuepf.clij.clearcl.exceptions.OpenCLException: OpenCL error: -4 -> CL_MEM_OBJECT_ALLOCATION_FAILURE
the source image remains locked, and so the "clear GPU memory" macro cant be run, in order to try again.
Perhaps catch openCL errors and force GPU memory clear if they happen. 
and/or make sure the source image doesn't remain locked, which confuses a naive user.
Workaround is to restart imageJ

**Comment by haesleinhuepf** [comment]
Hey @chalkie666,

I just tried to trace this down. Are you running on Windows by chance?

On my NVidia/Windows I see such error messages related to large kernels and/or large stacks. The problem might be that the GPU driver interrupts computation if it takes too long:
https://support.allegorithmic.com/documentation/spdoc/gpu-drivers-crash-with-long-computations-128745489.html

Future-self will dig deeper. But it would be good to know, on what OS you are running.

Thanks!

Cheers,
Robert

**Comment by chalkie666** [comment]
@haesleinhuepf yes it's win 10 64 but on both my laptop and workstation

I wasn't getting a pop up window with that error message in the link above. Rather an error message in IJ console

**Comment by haesleinhuepf** [comment]
I also didn't get that error message. But it was strange that the GPU exited after 5 seconds. I had that error a year ago on the microscope. If the image stack or the kernel become to large, the GPU hits the 5-second-timeout (on some systems 3 seconds). Afterwards, OpenCL throws weird error messages. The entry in the registry mentioned in the linked website makes the issue go away... on my machines...

**Comment by haesleinhuepf** [comment]
What I'm saying is: The GPU might not have run out of memory. The error message comes out of OpenCL and is misleading in this case...

**Comment by chalkie666** [comment]
@haesleinhuepf OK. So you suggest I edit the registry and see if it helps. I will try

**Comment by chalkie666** [comment]
@haesleinhuepf those registry settings don't exist on either of my machines... wonder if that means there is no timeout at all, or if the diver sets it by itself... but I'm not sure this is really the problem...?
The openCL error messages appear in the IJ console very quickly, 2-3 seconds, bot 5. Things that do work, but take a long time, do seem to work on both machines... Hmmmmmmmmmmmmmmmmm.....

Either way, would catching those open CL errors that appear in the IJ console and handling them gracefully be an option? Meaning that the input image isn't locked at the end, openCL memory clear happens with success, and the naive user gets a more intelligible error message... like "Whoops... looks like your openCL hardware device didn't like that. Perhaps it ran out of memory or the driver is too old? Consider trying a smaller image and/or kernel, and checking your openCL / GPU drivers are up to date?"

thoughts?

**Comment by haesleinhuepf** [comment]
Hi Dan,

I just fixed another workstation with the same issue (but a TITAN XP GPU) by adding these two entries in the registry. It worked nicely so I decided to put the solution in the troubleshooting section on the main page:
https://github.com/clij/clij/commit/eab68b9eeff0074af69a4d2f0ae94ee77fc2f1f0

Regarding the error message: The position of the error and its message is kind of random, because the operating system interrupts the GPU at a random point. 
I will add a general catch{} block later when things have stabilized (we are not far away from that though).

Thanks for testing!

Cheers,
Robert

**Comment by chalkie666** [comment]
@haesleinhuepf looking more carefully... more testing...
i can see that its not really running out of memory with the big images and big kernels. 
Windows 10 task manager shows me gpu processor and gpu memory usage on both machines, dedicated nvidia quadro p2000 or builtin intel HD 350 

Testing : image 512x512x258 (t1-head sample image, upscaled 2x2x2) and kernel 256x256x29 (diffraction psf)
1) Intel: Running without crash so far (albeit slowly) on intel HD 530 gpu, using 0.9 GB memory out of 7.9 GB total system memory, with 100% GPU processor usage, 44% CPU usage. 
2) nvidia: Crashes at start with CL memory allocation error on nvidia quadro P2000, with 5 GB onboard memory.

So the memory allocation error might not be that it is running out of memory, but something more subtle?  Maybe a difference between the openCL implementation of intel vs nvidia? Or a buggy driver? Hmmmm...

**Comment by haesleinhuepf** [comment]
Dan, have you tried the registry hack?




Get Outlook for Android







On Thu, Jan 31, 2019 at 3:49 PM +0100, "dan white" <notifications@github.com> wrote:












@haesleinhuepf looking more carefully... more testing...

i can see that its not really running out of memory with the big images and big kernels.

Windows 10 task manager shows me gpu processor and gpu memory usage on both machines, dedicated nvidia quadro p2000 or builtin intel HD 350


Testing : image 512x512x258 (t1-head sample image, upscaled 2x2x2) and kernel 256x256x29 (diffraction psf)

Intel: Running without crash so far (albeit slowly) on intel HD 530 gpu, using 0.9 GB memory out of 7.9 GB total system memory, with 100% GPU processor usage, 44% CPU usage.
nvidia: Crashes at start with CL memory allocation error on nvidia quadro P2000, with 5 GB onboard memory.



So the memory allocation error might not be that it is running out of memory, but something more subtle?  Maybe a difference between the openCL implementation of intel vs nvidia? Or a buggy driver? Hmmmm...

**Comment by chalkie666** [comment]
Tried the registry hack
Still crashes but takes longer to crash with same error

Maybe need a larger value for those 2 reg entries? Suggestion? 30 sec? 2
Min? What's that in hex?

D

**Comment by haesleinhuepf** [comment]
I entered 60 seconds (96 hex). How large are your images and PSF?




Get Outlook for Android







On Thu, Jan 31, 2019 at 4:10 PM +0100, "dan white" <notifications@github.com> wrote:










Tried the registry hack


Still crashes but takes longer to crash with same error





Maybe need a larger value for those 2 reg entries? Suggestion? 30 sec? 2


Min? What's that in hex?





D

**Comment by chalkie666** [comment]
@haesleinhuepf 
For the quadro p2000, i tried registry values for TdrDelay and TdrDdiDelay
of 96 and 222 (hex)  but still not big enough apparentl, still crashed but took longer to do so)
so i tried 555 (hex)     (  is 1365 decimal)
and was able to run 2 iterations of RL on GPU image sizes
source 400x400x25  (not that big)
kernel 128x128x64.  (very big)
GPU memory usage was under 1 GB, but GPU ran at 100% for several tens of min. 
I noticed that doing this makes the desktop unresponsive, even though the CPU is nowhere near being stressed.... so i guess the GPU at 100% might also slow the desktop to 1 frame every few seconds...
Nothing crashed though, and i got a result image, and it cleaned up after itself.

Clearly performance here is not great for these large kernels..., i suspect the kernel size is more of a problem than the source image size?  I might be wrong...
So I'm thinking about what advice to write in the wiki page, so users have reasonable expectations, and we avoid tons of bug reports:

If someone sees "GPU deconvolution", who is doing spim or very big widefield z stacks etc. and has CPU based deconv running as fast as it can, but looks for a faster method... they might try this method then wonder why it either crashes or is very slow (and bogs down the desktop) for large images and kernels.   I will try to explain why, and set reasonable expectations. 

Can we catch these type of open CL errors, 
and exit gracefully,
and give the user a helpful suggestions?:

try smaller images and kernels
try the registry trick
????

What do you think? 

cheers
D

**Comment by martinschorb** [comment]
Hi Robert,

I think I run into similar issues. Registry update did not help. The images/kernels are not that huge.

Is there anything else to try?

Martin

**Comment by haesleinhuepf** [comment]
Hey @martinschorb ,

apparently small kernels can get super slow in some cases. E.g. the median filter can get horribly slow at certain radii. Could you please go a bit into detail? How big are your images? How large is the kernel? What kind of operation is it? Is there maybe some source code online? What's your hardware configuration?

Thanks!

Cheers,
Robert

**Comment by martinschorb** [comment]
Hi Robert,

image size 2048x2048x180
"Blur3D on GPU" with kernel size 15x15x15
Win10, GPU nVidia GRID-P40-8Q 8GB (VMWare Horizon virtual workstation)

I came across your article in NatMeth (Congrats!!!) because I found the deadwood hardcopy on my desk this morning and started to play a bit.

This setup is what we would mainly use at EMBL for GPU-based processing. I guess   @tischer might also have some nice applications for this. Do you know if this is a Windows-only issue? If so, we could also use it to educate our users towards Linux.

**Comment by haesleinhuepf** [comment]
Ok, and what's the error message?

There was a user with similar reports with the same operation on the same hardware: 
https://forum.image.sc/t/clij-memory-allocation-failure-image-memory-limits/30719

Debugging memory usage with CLIJ_reportMemory and/or clijx.reportMemory could help. You might consider using the FLIP-FLOP strategy introduced in the link.

Let me know if this helps!

Cheer,,
Robert

**Comment by martinschorb** [comment]
Hi,
```java.lang.RuntimeException: net.haesleinhuepf.clij.clearcl.exceptions.OpenCLException: OpenCL error: -4 -> CL_MEM_OBJECT_ALLOCATION_FAILURE
	at net.haesleinhuepf.clij.clearcl.util.ElapsedTime.measure(ElapsedTime.java:114)
	at net.haesleinhuepf.clij.clearcl.util.ElapsedTime.measure(ElapsedTime.java:64)
	at net.haesleinhuepf.clij.clearcl.ClearCLKernel.run(ClearCLKernel.java:480)
	at net.haesleinhuepf.clij.clearcl.ClearCLKernel.run(ClearCLKernel.java:462)
	at net.haesleinhuepf.clij.utilities.CLKernelExecutor.lambda$enqueue$0(CLKernelExecutor.java:333)
	at net.haesleinhuepf.clij.clearcl.util.ElapsedTime.measure(ElapsedTime.java:97)
	at net.haesleinhuepf.clij.clearcl.util.ElapsedTime.measure(ElapsedTime.java:28)
	at net.haesleinhuepf.clij.utilities.CLKernelExecutor.enqueue(CLKernelExecutor.java:331)
	at net.haesleinhuepf.clij.CLIJ.lambda$execute$0(CLIJ.java:272)
	at net.haesleinhuepf.clij.clearcl.util.ElapsedTime.measure(ElapsedTime.java:97)
	at net.haesleinhuepf.clij.clearcl.util.ElapsedTime.measure(ElapsedTime.java:28)
	at net.haesleinhuepf.clij.CLIJ.execute(CLIJ.java:249)
	at net.haesleinhuepf.clij.CLIJ.execute(CLIJ.java:229)
	at net.haesleinhuepf.clij.kernels.Kernels.executeSeparableKernel(Kernels.java:705)
	at net.haesleinhuepf.clij.kernels.Kernels.blur(Kernels.java:558)
	at net.haesleinhuepf.clij.macro.modules.Blur3D.executeCL(Blur3D.java:31)
	at net.haesleinhuepf.clij.macro.AbstractCLIJPlugin.run(AbstractCLIJPlugin.java:381)
	at ij.plugin.filter.PlugInFilterRunner.processOneImage(PlugInFilterRunner.java:266)
	at ij.plugin.filter.PlugInFilterRunner.<init>(PlugInFilterRunner.java:114)
	at ij.IJ.runUserPlugIn(IJ.java:232)
	at ij.IJ.runPlugIn(IJ.java:193)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:66)
	at java.lang.Thread.run(Thread.java:748)
```

clInfo():
```Available CL backends:
  * net.haesleinhuepf.clij.clearcl.backend.jocl.ClearCLBackendJOCL@6aadb175
    Functional backend:net.haesleinhuepf.clij.clearcl.backend.jocl.ClearCLBackendJOCL@7c2b752d
    Best backend:net.haesleinhuepf.clij.clearcl.backend.jocl.ClearCLBackendJOCL@2a466ce0
Used CL backend: net.haesleinhuepf.clij.clearcl.backend.jocl.ClearCLBackendJOCL@7601d5fc
ClearCL: ClearCLBase [mClearCLBackendInterface=net.haesleinhuepf.clij.clearcl.backend.jocl.ClearCLBackendJOCL@7601d5fc, mPeerPointer=null]
  Number of platforms:1
  [0] NVIDIA CUDA
     Number of devices: 1
     Available devices: 
     [0] GRID P40-8Q 
        NumberOfComputeUnits: 30 
        Clock frequency: 1531 
        Version: 1.2 
        Extensions: cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_fp64 cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_d3d10_sharing cl_khr_d3d10_sharing cl_nv_d3d11_sharing cl_nv_copy_opts cl_khr_gl_event cl_nv_create_buffer 
        GlobalMemorySizeInBytes: 8543797248 
        LocalMemorySizeInBytes: 49152 
        MaxMemoryAllocationSizeInBytes: 2135949312 
        MaxWorkGroupSize: 1024 
        Compatible image types: [SignedNormalizedInt8, SignedNormalizedInt16, UnsignedNormalizedInt8, UnsignedNormalizedInt16, SignedInt8, SignedInt16, SignedInt32, UnsignedInt8, UnsignedInt16, UnsignedInt32, HalfFloat, Float]
Best GPU device for images: GRID P40-8Q
Best largest GPU device: GRID P40-8Q
Best CPU device: GRID P40-8Q```
```

**Comment by haesleinhuepf** [comment]
I think the first part (the decisive part) of the error message is missing :-(

**Comment by martinschorb** [comment]
```Clearing 
conversion target  ClearCLImage [mClearCLContext=ClearCLContext [device=ClearCLDevice [mClearCLPlatform=ClearCLPlatform [name=NVIDIA CUDA], name=GRID P40-8Q]], mImageType=IMAGE3D, mImageChannelOrder=R, mImageChannelDataType=UnsignedInt8, mDimensions=[2048, 2048, 176], getMemAllocMode()=Best, getHostAccessType()=ReadWrite, getKernelAccessType()=ReadWrite, getBackend()=net.haesleinhuepf.clij.clearcl.backend.jocl.ClearCLBackendJOCL@e4f2b86, getPeerPointer()=net.haesleinhuepf.clij.clearcl.ClearCLPeerPointer@2baba44a]
conversion target  ClearCLImage [mClearCLContext=ClearCLContext [device=ClearCLDevice [mClearCLPlatform=ClearCLPlatform [name=NVIDIA CUDA], name=GRID P40-8Q]], mImageType=IMAGE3D, mImageChannelOrder=R, mImageChannelDataType=UnsignedInt8, mDimensions=[2048, 2048, 176], getMemAllocMode()=Best, getHostAccessType()=ReadWrite, getKernelAccessType()=ReadWrite, getBackend()=net.haesleinhuepf.clij.clearcl.backend.jocl.ClearCLBackendJOCL@e4f2b86, getPeerPointer()=net.haesleinhuepf.clij.clearcl.ClearCLPeerPointer@45dcfe57]
```

**Comment by haesleinhuepf** [comment]
I mean, usually error messages start with something like:

```
java.lang.RuntimeException: net.haesleinhuepf.clij.clearcl.exceptions.OpenCLException: OpenCL error: -4 -> CL_MEM_OBJECT_ALLOCATION_FAILURE
```

and end with

```
Caused by: net.haesleinhuepf.clij.clearcl.exceptions.OpenCLException: OpenCL error: -4 -> CL_MEM_OBJECT_ALLOCATION_FAILURE
	at net.haesleinhuepf.clij.clearcl.backend.BackendUtils.checkOpenCLError(BackendUtils.java:346)
	at net.haesleinhuepf.clij.clearcl.backend.jocl.ClearCLBackendJOCL.lambda$enqueueKernelExecution$21(ClearCLBackendJOCL.java:736)
	at net.haesleinhuepf.clij.clearcl.backend.BackendUtils.checkExceptions(BackendUtils.java:171)
	at net.haesleinhuepf.clij.clearcl.backend.jocl.ClearCLBackendJOCL.enqueueKernelExecution(ClearCLBackendJOCL.java:735)
	at net.haesleinhuepf.clij.clearcl.ClearCLKernel.lambda$run$0(ClearCLKernel.java:492)
	at net.haesleinhuepf.clij.clearcl.util.ElapsedTime.measure(ElapsedTime.java:97)
	... 23 more
```

These are the interesting parts because they tell me what goes wrong and where ;-)

**Comment by martinschorb** [comment]
Sorry,
these were cut for some reason when pasting in here, next try...

```

java.lang.RuntimeException: net.haesleinhuepf.clij.clearcl.exceptions.OpenCLException: OpenCL error: -4 -> CL_MEM_OBJECT_ALLOCATION_FAILURE
	at net.haesleinhuepf.clij.clearcl.util.ElapsedTime.measure(ElapsedTime.java:114)
	at net.haesleinhuepf.clij.clearcl.util.ElapsedTime.measure(ElapsedTime.java:64)
	at net.haesleinhuepf.clij.clearcl.ClearCLKernel.run(ClearCLKernel.java:480)
	at net.haesleinhuepf.clij.clearcl.ClearCLKernel.run(ClearCLKernel.java:462)
	at net.haesleinhuepf.clij.utilities.CLKernelExecutor.lambda$enqueue$0(CLKernelExecutor.java:333)
	at net.haesleinhuepf.clij.clearcl.util.ElapsedTime.measure(ElapsedTime.java:97)
	at net.haesleinhuepf.clij.clearcl.util.ElapsedTime.measure(ElapsedTime.java:28)
	at net.haesleinhuepf.clij.utilities.CLKernelExecutor.enqueue(CLKernelExecutor.java:331)
	at net.haesleinhuepf.clij.CLIJ.lambda$execute$0(CLIJ.java:272)
	at net.haesleinhuepf.clij.clearcl.util.ElapsedTime.measure(ElapsedTime.java:97)
	at net.haesleinhuepf.clij.clearcl.util.ElapsedTime.measure(ElapsedTime.java:28)
	at net.haesleinhuepf.clij.CLIJ.execute(CLIJ.java:249)
	at net.haesleinhuepf.clij.CLIJ.execute(CLIJ.java:229)
	at net.haesleinhuepf.clij.kernels.Kernels.executeSeparableKernel(Kernels.java:722)
	at net.haesleinhuepf.clij.kernels.Kernels.blur(Kernels.java:558)
	at net.haesleinhuepf.clij.macro.modules.Blur3D.executeCL(Blur3D.java:31)
	at net.haesleinhuepf.clij.macro.AbstractCLIJPlugin.run(AbstractCLIJPlugin.java:381)
	at ij.plugin.filter.PlugInFilterRunner.processOneImage(PlugInFilterRunner.java:266)
	at ij.plugin.filter.PlugInFilterRunner.<init>(PlugInFilterRunner.java:114)
	at ij.IJ.runUserPlugIn(IJ.java:232)
	at ij.IJ.runPlugIn(IJ.java:193)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:63)
	at java.lang.Thread.run(Thread.java:748)
Caused by: net.haesleinhuepf.clij.clearcl.exceptions.OpenCLException: OpenCL error: -4 -> CL_MEM_OBJECT_ALLOCATION_FAILURE
	at net.haesleinhuepf.clij.clearcl.backend.BackendUtils.checkOpenCLError(BackendUtils.java:346)
	at net.haesleinhuepf.clij.clearcl.backend.jocl.ClearCLBackendJOCL.lambda$enqueueKernelExecution$21(ClearCLBackendJOCL.java:736)
	at net.haesleinhuepf.clij.clearcl.backend.BackendUtils.checkExceptions(BackendUtils.java:171)
	at net.haesleinhuepf.clij.clearcl.backend.jocl.ClearCLBackendJOCL.enqueueKernelExecution(ClearCLBackendJOCL.java:735)
	at net.haesleinhuepf.clij.clearcl.ClearCLKernel.lambda$run$0(ClearCLKernel.java:492)
	at net.haesleinhuepf.clij.clearcl.util.ElapsedTime.measure(ElapsedTime.java:97)
...
```

**Comment by haesleinhuepf** [comment]
Ok, you're runnning Blur3D from the menu, right?

**Comment by haesleinhuepf** [comment]
Could you please try running [this macro](https://forum.image.sc/t/clij-memory-allocation-failure-image-memory-limits/30719/6)?

```
run("Close All");
// init GPU
run("CLIJ Macro Extensions", "cl_device=");
Ext.CLIJ_clear();

for (i = 0; i < 100; i++) {
	// Get test data
	width = 1024;
	height = 1024;
	slices = 100 * i;
	newImage("image" + i, "8-bit ramp", width, height, slices);
	
	// push image to GPU
	Ext.CLIJ_push("image" + i);
	
	if(i > 0) {
		Ext.CLIJ_blur3D("image" + i, "image" + (i-1), 1, 1, 0);
	}
	
	// cleanup imagej
	run("Close All");
	
	Ext.CLIJ_reportMemory();
	Ext.CLIJ_clear();
}
```

It is supposed to crash. I'd like to know when ;-)

**Comment by martinschorb** [comment]
It started throwing the MEM_OBJECT_ALLOCATION errors at around i=22 or so...

**Comment by martinschorb** [comment]
Full errors look like this:
```
net.haesleinhuepf.clij.clearcl.exceptions.OpenCLException: OpenCL error: -4 -> CL_MEM_OBJECT_ALLOCATION_FAILURE
	at net.haesleinhuepf.clij.clearcl.backend.BackendUtils.checkOpenCLError(BackendUtils.java:346)
	at net.haesleinhuepf.clij.clearcl.backend.jocl.ClearCLBackendJOCL.lambda$enqueueWriteToBufferRegion$25(ClearCLBackendJOCL.java:830)
	at net.haesleinhuepf.clij.clearcl.backend.BackendUtils.checkExceptions(BackendUtils.java:171)
	at net.haesleinhuepf.clij.clearcl.backend.jocl.ClearCLBackendJOCL.enqueueWriteToBufferRegion(ClearCLBackendJOCL.java:828)
	at net.haesleinhuepf.clij.clearcl.ClearCLBuffer.readFrom(ClearCLBuffer.java:667)
	at net.haesleinhuepf.clij.converters.implementations.ImagePlusToClearCLBufferConverter.convertBigImage(ImagePlusToClearCLBufferConverter.java:162)
	at net.haesleinhuepf.clij.converters.implementations.ImagePlusToClearCLBufferConverter.convert(ImagePlusToClearCLBufferConverter.java:88)
	at net.haesleinhuepf.clij.converters.implementations.ImagePlusToClearCLBufferConverter.convert(ImagePlusToClearCLBufferConverter.java:24)
	at net.haesleinhuepf.clij.CLIJ.convert(CLIJ.java:462)
	at net.haesleinhuepf.clij.CLIJ.push(CLIJ.java:399)
	at net.haesleinhuepf.clij.macro.CLIJHandler.pushToGPU(CLIJHandler.java:229)
	at net.haesleinhuepf.clij.macro.modules.Push.executeCL(Push.java:43)
	at net.haesleinhuepf.clij.macro.CLIJHandler.lambda$handleExtension$0(CLIJHandler.java:144)
	at net.haesleinhuepf.clij.clearcl.util.ElapsedTime.measure(ElapsedTime.java:97)
	at net.haesleinhuepf.clij.clearcl.util.ElapsedTime.measure(ElapsedTime.java:28)
	at net.haesleinhuepf.clij.macro.CLIJHandler.handleExtension(CLIJHandler.java:51)
	at ij.macro.ExtensionDescriptor.dispatch(ExtensionDescriptor.java:288)
	at ij.macro.Functions.doExt(Functions.java:4787)
	at ij.macro.Functions.getStringFunction(Functions.java:276)
	at ij.macro.Interpreter.getStringTerm(Interpreter.java:1407)
	at ij.macro.Interpreter.getString(Interpreter.java:1385)
	at ij.macro.Interpreter.doStatement(Interpreter.java:329)
	at ij.macro.Interpreter.doBlock(Interpreter.java:671)
	at ij.macro.Interpreter.doStatement(Interpreter.java:320)
	at ij.macro.Interpreter.doFor(Interpreter.java:593)
	at ij.macro.Interpreter.doStatement(Interpreter.java:302)
	at ij.macro.Interpreter.doStatements(Interpreter.java:261)
	at ij.macro.Interpreter.run(Interpreter.java:157)
	at ij.macro.Interpreter.run(Interpreter.java:91)
	at ij.macro.Interpreter.run(Interpreter.java:102)
	at ij.plugin.Macro_Runner.runMacro(Macro_Runner.java:161)
	at ij.IJ.runMacro(IJ.java:148)
	at ij.IJ.runMacro(IJ.java:137)
	at net.imagej.legacy.IJ1Helper$3.call(IJ1Helper.java:1108)
	at net.imagej.legacy.IJ1Helper$3.call(IJ1Helper.java:1104)
	at net.imagej.legacy.IJ1Helper.runMacroFriendly(IJ1Helper.java:1055)
	at net.imagej.legacy.IJ1Helper.runMacro(IJ1Helper.java:1104)
	at net.imagej.legacy.plugin.IJ1MacroEngine.eval(IJ1MacroEngine.java:147)
	at org.scijava.script.ScriptModule.run(ScriptModule.java:160)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:228)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.NullPointerException
	at net.haesleinhuepf.clij.CLIJ.createCLBuffer(CLIJ.java:333)
	at net.haesleinhuepf.clij.macro.AbstractCLIJPlugin.createOutputBufferFromSource(AbstractCLIJPlugin.java:210)
	at net.haesleinhuepf.clij.macro.CLIJHandler.getFromCacheOrCreateByPlugin(CLIJHandler.java:177)
	at net.haesleinhuepf.clij.macro.CLIJHandler.lambda$handleExtension$0(CLIJHandler.java:110)
	at net.haesleinhuepf.clij.clearcl.util.ElapsedTime.measure(ElapsedTime.java:97)
	at net.haesleinhuepf.clij.clearcl.util.ElapsedTime.measure(ElapsedTime.java:28)
	at net.haesleinhuepf.clij.macro.CLIJHandler.handleExtension(CLIJHandler.java:51)
	at ij.macro.ExtensionDescriptor.dispatch(ExtensionDescriptor.java:288)
	at ij.macro.Functions.doExt(Functions.java:4787)
	at ij.macro.Functions.getStringFunction(Functions.java:276)
	at ij.macro.Interpreter.getStringTerm(Interpreter.java:1407)
	at ij.macro.Interpreter.getString(Interpreter.java:1385)
	at ij.macro.Interpreter.doStatement(Interpreter.java:329)
	at ij.macro.Interpreter.doBlock(Interpreter.java:671)
	at ij.macro.Interpreter.doStatement(Interpreter.java:320)
	at ij.macro.Interpreter.doIf(Interpreter.java:1049)
	at ij.macro.Interpreter.doStatement(Interpreter.java:296)
	at ij.macro.Interpreter.doBlock(Interpreter.java:671)
	at ij.macro.Interpreter.doStatement(Interpreter.java:320)
	at ij.macro.Interpreter.doFor(Interpreter.java:593)
	at ij.macro.Interpreter.doStatement(Interpreter.java:302)
	at ij.macro.Interpreter.doStatements(Interpreter.java:261)
	at ij.macro.Interpreter.run(Interpreter.java:157)
	at ij.macro.Interpreter.run(Interpreter.java:91)
	at ij.macro.Interpreter.run(Interpreter.java:102)
	at ij.plugin.Macro_Runner.runMacro(Macro_Runner.java:161)
	at ij.IJ.runMacro(IJ.java:148)
	at ij.IJ.runMacro(IJ.java:137)
	at net.imagej.legacy.IJ1Helper$3.call(IJ1Helper.java:1108)
	at net.imagej.legacy.IJ1Helper$3.call(IJ1Helper.java:1104)
	at net.imagej.legacy.IJ1Helper.runMacroFriendly(IJ1Helper.java:1055)
	at net.imagej.legacy.IJ1Helper.runMacro(IJ1Helper.java:1104)
	at net.imagej.legacy.plugin.IJ1MacroEngine.eval(IJ1MacroEngine.java:147)
	at org.scijava.script.ScriptModule.run(ScriptModule.java:160)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:228)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by martinschorb** [comment]
IJ log at the critical transistion:

```
...

GPU contains 4 images.
- image19[net.haesleinhuepf.clij.clearcl.ClearCLPeerPointer@36276eb] 2.0 Gb
- image19[net.haesleinhuepf.clij.clearcl.ClearCLPeerPointer@2405fff1]* 2.0 Gb
- image20[net.haesleinhuepf.clij.clearcl.ClearCLPeerPointer@37a99fa8] 2.0 Gb
- image20[net.haesleinhuepf.clij.clearcl.ClearCLPeerPointer@3f713368]* 2.0 Gb
= 7.8 Gb
* some images are stored twice for technical reasons.
 
GPU contains 4 images.
- image20[net.haesleinhuepf.clij.clearcl.ClearCLPeerPointer@3850a45f] 2.1 Gb
- image20[net.haesleinhuepf.clij.clearcl.ClearCLPeerPointer@181f9c32]* 2.1 Gb
- image21[net.haesleinhuepf.clij.clearcl.ClearCLPeerPointer@444c0d09] 2.1 Gb
- image21[net.haesleinhuepf.clij.clearcl.ClearCLPeerPointer@18dc7d39]* 2.1 Gb
= 8.2 Gb
* some images are stored twice for technical reasons.
 
GPU contains 0 images.
= 0.0 b
 
GPU contains 0 images.
= 0.0 b
 ...
```

So it is filling all 8GB with 4 images.

**Comment by martinschorb** [comment]
Probably this is specific to the Blur3d?
However, why is image20 still in the GPU even after calling ```Ext.CLIJ_clear();```?
Since its size has changed I assume it is just mislabeled and another image...

**Comment by haesleinhuepf** [comment]
Hey @martinschorb ,

after reading [the thread](https://forum.image.sc/t/clij-memory-allocation-failure-image-memory-limits/30719/7) on the image.sc forum, I remember what the issue was: For speed reasons, CLIJ makes a copy (actually a conversion) of your image just before blurring and also converts it back afterwards. This increases performance, but unfortunately also increases memory consumption. In order to avoid that, one has to call the CLIJ-API more directly, e.g. using Jython: The following example is adapted from [here](https://github.com/clij/clij-docs/blob/master/src/main/jython/blur.py):

```
from ij import IJ;
from net.haesleinhuepf.clij import CLIJ;

# get current image
imp = IJ.getImage();
imp.show();

# init GPU
clij = CLIJ.getInstance();

# push image to GPU
input = clij.push(imp);

# reserve memory for output, same size and type as input
output = clij.create(input);

# apply a Gaussian blur on GPU
clij.op().blur3D(input, output, 5, 5, 5);

# show result
clij.pull(output).show();

# clean up
input.close();
output.close();
```

In CLIJ2 there will be some simplification for this case. I can let you know as soon as its beta is out.

In the meantime: Would you mind trying that script?

Thanks for your patience!

Cheers,
Robert

**Comment by haesleinhuepf** [comment]
> However, why is image20 still in the GPU even after calling `Ext.CLIJ_clear();`?
Immediately after calling clear, the list should be empty. 

During the loop, two images are created. One with `push()` and the other as target image during this operation:
```
Ext.CLIJ_blur3D("image" + i, "image" + (i-1), 1, 1, 0);
```

And again CLIJ_blur3D internally makes two copies. When working with 2 GB images, this exceeds your 8 GB memory...

**Comment by martinschorb** [comment]
This makes a lot of sense.
For testing your Jython script I run into some dependency issues, but don't worry. It seems that there is nothing generally wrong with the behaviour because the filters run as long as the GPU memory is kept in mind.

Cheers and thanks a lot,
Martin

**Comment by haesleinhuepf** [comment]
> dependency

Which? (-:

**Comment by martinschorb** [comment]
Import error: No module named haesleinhuepf

don't worry, I tried with ImageJ's macro editor. Probably I am just missing an update site...

**Comment by haesleinhuepf** [comment]
```
from net.haesleinhuepf.clij import CLIJ;
```

CLIJ lives in clij-core.jar, usually in the /jars/ subdirectory of Fiji. I guess you have the clij update site enabled, right?

**Comment by martinschorb** [comment]
exactly...

**Comment by martinschorb** [comment]
OK, solved.
The VM was reset and therefore reverted to the original Fiji without clij...

**Comment by haesleinhuepf** [comment]
Ah ok. Great. I hope the Jython-trick helps you getting your images processed. By activating the clij2 update site, you get jython auto-completion in the script editor:

![image](https://user-images.githubusercontent.com/12660498/73763544-d6de7080-4771-11ea-9d7a-201e6261b096.png)

Experimental still, but maybe this helps as well ;-)

**Comment by ReneHaensel** [comment]
I have roughly a similar problem. Some research on the error message `net.haesleinhuepf.clij.clearcl.exceptions.OpenCLException: OpenCL error: -4 -> CL_MEM_OBJECT_ALLOCATION_FAILURE`
led to the conclusion that it is the _MaxMemoryAllocationSizeInBytes_.
Is the _MaxMemoryAllocationSizeInBytes_ a fixed value due to the hardware or is it extensible?

I have tried this on two diffrent Nvidia cards. The Quadro K5000 has about 3GB of _GlobalMemory_ and only 890MB of that is _MaxMemoryAllocation_. On a GeForce GTX 1060 it is 6Gb _GlobalMemory_ and 1.5GB _MaxMemoryAllocation_.

**Comment by haesleinhuepf** [comment]
> Is the _MaxMemoryAllocationSizeInBytes_ a fixed value due to the hardware

It appears a hardware limitation, yes.
